"""fase3_user_isolation

Revision ID: c9c1383b04bd
Revises: fef526537305
Create Date: 2026-05-16 09:22:43.640108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9c1383b04bd'
down_revision: Union[str, Sequence[str], None] = 'fef526537305'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # No DDL changes needed — schema already includes all fase3 tables (users, system_config, etc.)
    # from initial_schema migration.
    # ### end Alembic commands ###

    # Assignar projectes orfes al primer admin
    op.execute("""
        UPDATE projects
        SET user_id = (
            SELECT id FROM users WHERE role = 'admin' ORDER BY created_at LIMIT 1
        )
        WHERE user_id IS NULL
        AND EXISTS (SELECT 1 FROM users WHERE role = 'admin')
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
